# Generated by Django 4.2.16 on 2024-11-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfflipbook',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
